# Generated by Django 3.0.2 on 2021-01-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0006_auto_20210104_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click link above to view post', max_length=255),
        ),
    ]
